apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_1
  labels:
    app: app_1
spec:
  selector:
    matchLabels:
      app: app_1
  template:
    metadata:
      labels:
        app: app_1
    spec:
      containers:
        - name: app_1
          image: nginx