apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app_0
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    path: kustomize/app_0/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}