apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster_1
  namespace: flux-system
spec:
  interval: 10m1s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: clusters/cluster_1
  prune: true