apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster_1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ''
    path: kustomize/clusters/cluster_1/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}